fan_site/config/routes.rb
Rails.application.routes.draw do
  root :to => 'novels#index'

  resources :novels do
    resources :reviews
  end
end

fan_site/app/models/novel.rb
class Novel < ActiveRecord::Base
  has_many :reviews

  validates :author, :presence => true
  validates :title, :presence => true
  validates :description, :presence => true
end

fan_site/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :novel

  validates :user_name, :presence =>true
  validates :description, :presence =>true
end

fan_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

fan_site/app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  def index
    @novels = Novel.all.sort_by {|novel|
      (novel.rating + (1/(Time.new - novel.created_at) * 20000))
    }
    @novels.reverse!
  end

  def show
    @novel = Novel.find(params[:id])
  end

  def new
    @novel = Novel.new
  end

  def create
    @novel = Novel.new(novel_params)
    @novel.rating = 0
    if @novel.save
      redirect_to novels_path
    else
      render :new
    end
  end

  def edit
    @novel = Novel.find(params[:id])
    if params[:upvote]
      new_rating = @novel.rating + 1
      @novel.update(rating: new_rating)
      redirect_to novels_path
    end
  end

  def update
    @novel = Novel.find(params[:id])
    if @novel.update(novel_params)
      redirect_to novels_path
    else
      render :edit
    end
  end

  def destroy
    @novel = Novel.find(params[:id])
    @novel.destroy
    redirect_to novels_path
  end

private
  def novel_params
    params.require(:novel).permit(:author, :title, :description)
  end

end

fan_site/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @novel = Novel.find(params[:novel_id])
    @review = @novel.reviews.new
  end

  def create
    @novel = Novel.find(params[:novel_id])
    @review = @novel.reviews.new(review_params)
    if @review.save
      redirect_to novel_path(@review.novel)
    else
      render :new
    end
  end

  def destroy
    @novel = Novel.find(params[:novel_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to novel_path(@novel)
  end


  private
    def review_params
      params.require(:review).permit(:user_name, :description)
    end

end

fan_site/app/helpers/application_helper.rb
module ApplicationHelper
end

fan_site/app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

fan_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classy Ladies, Trashy Books</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,500' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="jumbotron main-jumbotron">
    <br>
    <br>
    <br>
    <br>
    <h1 class="title">Trashy Books for Classy Ladies</h1>
    <br>
    <br>
    <br>
  </div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
          <ul class="nav navbar-nav navbar-left">
            <li><a class="navbar-link" href="/">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-left">
            <li><a class="navbar-link" href="/novels/new">Add a novel</a></li>
          </ul>
      </div>
    </div>
  </nav>
  <div class = "container">
  <%= yield %>
  </div>
</body>
</html>

fan_site/app/views/novels/_form.html.erb
<%= render "layouts/errors", :object => @novel %>

<center>
<%= form_for @novel do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :description%>
    <br>
    <%= f.text_area :description, cols: "80", rows: "10"%>
  </div>
    <%= f.submit %>
  <% end %>
</center>

fan_site/app/views/novels/edit.html.erb
<h1>Edit novel</h1>

<%= render 'form' %>

fan_site/app/views/novels/index.html.erb
<ul>
  <% @novels.each do |novel| %>
    <li>
      <br>
      <div class="novel-display">
        <%= link_to novel.title, novel_path(novel) %> <%= link_to content_tag(:span, "", class:"glyphicon glyphicon-heart"), edit_novel_path(novel.id, upvote:true) %>
      </div>
      <small><%= novel.rating %> Likes</small>
      <small>Posted <%= ((Time.now - novel.created_at)/60).round(0)%> minutes ago </small>
      <br>
    </li>
  <% end %>
</ul>

<span class="glyphicon"></span>

fan_site/app/views/novels/new.html.erb
<center>
<h1>Add a Novel!</h1>
</center>
<br>
<br>

<%= render 'form' %>

fan_site/app/views/novels/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="novel-header">
     <%= @novel.title %>
  </div>
  <center>
  <div class= "novel-details">
    <li><strong> Author:</strong>  <%= @novel.author %>
       <strong> Likes:</strong>  <%=@novel.rating%></li>
  </div>
  </center>
  <hr>
  <div class= "novel-description">
  <li><strong>Description:</strong> <%=@novel.description %></li>
  </div>
  <br>
  <br>
  <center>
  <li><p><%= link_to "Edit", edit_novel_path(@novel), class:"btn btn-default" %>
         <%= link_to "Delete", novel_path(@novel),
                              :data => {:confirm =>"You sure?",
                              :method => "delete"}, class:"btn btn-default" %>
        <%= link_to "Review", new_novel_review_path(@novel), class:"btn btn-danger" %></p></li>

  </center>
  <br>
  <br>
  <% if @novel.reviews.any? %>
    <div class = "review-title">
    <p> Reviews </p>
    <br>
    </div>
    <ul>
      <% @novel.reviews.each do |review| %>
        <div class= "review-display">
          <li><strong><%= review.user_name %></strong>, <%= review.created_at %></li>
          <li> <%= review.description %>
          <%= link_to "Delete", novel_review_path(@novel, review),
                                    :data => {:confirm => "Are you sure?",
                                    :method => "delete"}, class:"btn btn-default" %> </li>
        </div>
        <br>
      <% end %>
    </ul>
  <% end %>
</div>

fan_site/app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<div class = "container">
  <%= form_for [@novel, @review] do |f| %>
    <div class="form-group">
      <%=  f.label :Name %>
      <br>
      <%=  f.text_field  :user_name %>
    </div>
    <div class="form-group">
      <%=  f.label :review %>
      <br>
      <%=  f.text_area :description, cols: "80", rows: "10" %>
    </div>
    <p><%= f.submit %></p>
  <% end %>
</div>

fan_site/app/views/reviews/new.html.erb
<div class = "container">
<center>
<h1><%= @novel.title %></h1>
</center>
<br>
<br>
<%= render 'form' %>
</div>